//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicYear
    {
        public AcademicYear()
        {
            this.Blocks = new HashSet<Block>();
            this.Courses = new HashSet<Course>();
            this.Dorms = new HashSet<Dorm>();
            this.DutyTeams = new HashSet<DutyTeam>();
            this.GradeTables = new HashSet<GradeTable>();
            this.Permissions = new HashSet<Permission>();
            this.Terms = new HashSet<Term>();
        }
    
        public int id { get; set; }
        public System.DateTime GraduationDate { get; set; }
    
        public virtual ICollection<Block> Blocks { get; set; }
        public virtual ICollection<Course> Courses { get; set; }
        public virtual ICollection<Dorm> Dorms { get; set; }
        public virtual ICollection<DutyTeam> DutyTeams { get; set; }
        public virtual ICollection<GradeTable> GradeTables { get; set; }
        public virtual ICollection<Permission> Permissions { get; set; }
        public virtual ICollection<Term> Terms { get; set; }
    }
}
