//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApiPermission
    {
        public ApiPermission()
        {
            this.ApiPermissionGroups = new HashSet<ApiPermissionGroup>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string ResourceUri { get; set; }
        public bool Read { get; set; }
        public bool Create { get; set; }
        public bool Modify { get; set; }
        public bool Delete { get; set; }
    
        public virtual ICollection<ApiPermissionGroup> ApiPermissionGroups { get; set; }
    }
}
