//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttendanceSubmissionStatu
    {
        public int id { get; set; }
        public int SectionId { get; set; }
        public System.DateTime Day { get; set; }
        public int StatusId { get; set; }
        public int UpdateCount { get; set; }
        public System.DateTime TimeStamp { get; set; }
    
        public virtual AttendanceStatu AttendanceStatu { get; set; }
        public virtual Section Section { get; set; }
    }
}
