//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.RequestableCourses = new HashSet<RequestableCourse>();
            this.Sections = new HashSet<Section>();
        }
    
        public int id { get; set; }
        public string BlackBaudID { get; set; }
        public string Name { get; set; }
        public int AcademicYear { get; set; }
        public int DepartmentID { get; set; }
        public int LengthInTerms { get; set; }
        public bool goesToSchoology { get; set; }
        public int SchoologyId { get; set; }
    
        public virtual AcademicYear AcademicYear1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<RequestableCourse> RequestableCourses { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
