//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CourseRequest
    {
        public CourseRequest()
        {
            this.APRequests = new HashSet<APRequest>();
        }
    
        public int id { get; set; }
        public int StudentId { get; set; }
        public int TermId { get; set; }
        public int CourseId { get; set; }
        public bool IsGlobalAlternate { get; set; }
        public bool IsSecondary { get; set; }
    
        public virtual ICollection<APRequest> APRequests { get; set; }
        public virtual RequestableCourse RequestableCourse { get; set; }
        public virtual Student Student { get; set; }
        public virtual Term Term { get; set; }
    }
}
