//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credit
    {
        public Credit()
        {
            this.Sections = new HashSet<Section>();
        }
    
        public int id { get; set; }
        public int CreditTypeId { get; set; }
        public int CreditValueId { get; set; }
        public string Notes { get; set; }
        public int StudentId { get; set; }
    
        public virtual GradeTableEntry Type { get; set; }
        public virtual GradeTableEntry Value { get; set; }
        public virtual Student Student { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
