//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoogleCalendar
    {
        public GoogleCalendar()
        {
            this.StudentCalendarSpecialPermissions = new HashSet<StudentCalendarSpecialPermission>();
            this.Faculties = new HashSet<Faculty>();
        }
    
        public int id { get; set; }
        public string CalendarId { get; set; }
        public string FacultyPermission { get; set; }
        public string StudentPermission { get; set; }
        public string CalendarName { get; set; }
    
        public virtual ICollection<StudentCalendarSpecialPermission> StudentCalendarSpecialPermissions { get; set; }
        public virtual ICollection<Faculty> Faculties { get; set; }
    }
}
