//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GradeTableEntry
    {
        public GradeTableEntry()
        {
            this.APRequests = new HashSet<APRequest>();
            this.AttendanceMarkings = new HashSet<AttendanceMarking>();
            this.CreditsTyped = new HashSet<Credit>();
            this.CreditsValued = new HashSet<Credit>();
            this.StudentComments = new HashSet<StudentComment>();
            this.StudentComments1 = new HashSet<StudentComment>();
            this.StudentComments2 = new HashSet<StudentComment>();
            this.StudentComments3 = new HashSet<StudentComment>();
        }
    
        public int id { get; set; }
        public int GradeTableID { get; set; }
        public string Name { get; set; }
        public int Value { get; set; }
    
        public virtual ICollection<APRequest> APRequests { get; set; }
        public virtual ICollection<AttendanceMarking> AttendanceMarkings { get; set; }
        public virtual ICollection<Credit> CreditsTyped { get; set; }
        public virtual ICollection<Credit> CreditsValued { get; set; }
        public virtual GradeTable GradeTable { get; set; }
        public virtual ICollection<StudentComment> StudentComments { get; set; }
        public virtual ICollection<StudentComment> StudentComments1 { get; set; }
        public virtual ICollection<StudentComment> StudentComments2 { get; set; }
        public virtual ICollection<StudentComment> StudentComments3 { get; set; }
    }
}
