//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryPass
    {
        public int id { get; set; }
        public System.DateTime LibraryDay { get; set; }
        public Nullable<int> StudyHallSignatureId { get; set; }
        public Nullable<int> LibrarySignatureId { get; set; }
        public string Notes { get; set; }
        public int StudentId { get; set; }
    
        public virtual TimeStampedSignature TimeStampedSignature { get; set; }
        public virtual TimeStampedSignature TimeStampedSignature1 { get; set; }
        public virtual Student Student { get; set; }
    }
}
