//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public Permission()
        {
            this.Faculties = new HashSet<Faculty>();
            this.WebPages = new HashSet<WebPage>();
            this.Students = new HashSet<Student>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int AcademicYear { get; set; }
    
        public virtual AcademicYear AcademicYear1 { get; set; }
        public virtual ICollection<Faculty> Faculties { get; set; }
        public virtual ICollection<WebPage> WebPages { get; set; }
        public virtual ICollection<Student> Students { get; set; }
    }
}
