//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestableCourse
    {
        public RequestableCourse()
        {
            this.CourseRequests = new HashSet<CourseRequest>();
        }
    
        public int id { get; set; }
        public int TermId { get; set; }
        public int CourseId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual ICollection<CourseRequest> CourseRequests { get; set; }
        public virtual Term Term { get; set; }
    }
}
