//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatingChart
    {
        public SeatingChart()
        {
            this.SeatingChartSeats = new HashSet<SeatingChartSeat>();
        }
    
        public int id { get; set; }
        public int SectionId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SeatingChartSeat> SeatingChartSeats { get; set; }
        public virtual Section Section { get; set; }
    }
}
