//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeatingChartSeat
    {
        public int id { get; set; }
        public int ChartId { get; set; }
        public int Row { get; set; }
        public int Column { get; set; }
        public Nullable<int> StudentId { get; set; }
    
        public virtual SeatingChart SeatingChart { get; set; }
        public virtual Student Student { get; set; }
    }
}
