//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Section
    {
        public Section()
        {
            this.AttendanceMarkings = new HashSet<AttendanceMarking>();
            this.AttendanceSubmissionStatus = new HashSet<AttendanceSubmissionStatu>();
            this.CommentHeaders = new HashSet<CommentHeader>();
            this.SeatingCharts = new HashSet<SeatingChart>();
            this.APRequests = new HashSet<APRequest>();
            this.Credits = new HashSet<Credit>();
            this.Students = new HashSet<Student>();
            this.Teachers = new HashSet<Faculty>();
            this.Terms = new HashSet<Term>();
        }
    
        public int id { get; set; }
        public int CourseIndex { get; set; }
        public int SectionNumber { get; set; }
        public bool getsComments { get; set; }
        public int BlockIndex { get; set; }
        public int SchoologyId { get; set; }
        public bool FromBlackbaud { get; set; }
    
        public virtual ICollection<AttendanceMarking> AttendanceMarkings { get; set; }
        public virtual ICollection<AttendanceSubmissionStatu> AttendanceSubmissionStatus { get; set; }
        public virtual Block Block { get; set; }
        public virtual ICollection<CommentHeader> CommentHeaders { get; set; }
        public virtual Course Course { get; set; }
        public virtual ICollection<SeatingChart> SeatingCharts { get; set; }
        public virtual ICollection<APRequest> APRequests { get; set; }
        public virtual ICollection<Credit> Credits { get; set; }
        public virtual ICollection<Student> Students { get; set; }
        public virtual ICollection<Faculty> Teachers { get; set; }
        public virtual ICollection<Term> Terms { get; set; }
    }
}
