//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentCalendarSpecialPermission
    {
        public int id { get; set; }
        public int StudentId { get; set; }
        public int CalendarId { get; set; }
        public string Role { get; set; }
    
        public virtual GoogleCalendar GoogleCalendar { get; set; }
        public virtual Student Student { get; set; }
    }
}
