//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.CommentHeaders = new HashSet<CommentHeader>();
            this.CourseRequests = new HashSet<CourseRequest>();
            this.CourseRequestComments = new HashSet<CourseRequestComment>();
            this.RequestableCourses = new HashSet<RequestableCourse>();
            this.WednesdaySchedules = new HashSet<WednesdaySchedule>();
            this.Sections = new HashSet<Section>();
        }
    
        public int id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.DateTime TermComments { get; set; }
        public int AcademicYearID { get; set; }
        public int SchoologyId { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual ICollection<CommentHeader> CommentHeaders { get; set; }
        public virtual ICollection<CourseRequest> CourseRequests { get; set; }
        public virtual ICollection<CourseRequestComment> CourseRequestComments { get; set; }
        public virtual ICollection<RequestableCourse> RequestableCourses { get; set; }
        public virtual ICollection<WednesdaySchedule> WednesdaySchedules { get; set; }
        public virtual ICollection<Section> Sections { get; set; }
    }
}
