//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeStampedSignature
    {
        public TimeStampedSignature()
        {
            this.LibraryPasses = new HashSet<LibraryPass>();
            this.LibraryPasses1 = new HashSet<LibraryPass>();
        }
    
        public int id { get; set; }
        public int FacultyId { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public Nullable<System.DateTime> AltTimeStamp { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual ICollection<LibraryPass> LibraryPasses { get; set; }
        public virtual ICollection<LibraryPass> LibraryPasses1 { get; set; }
    }
}
