//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebhostEntities : DbContext
    {
        public WebhostEntities()
            : base("name=WebhostEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AcademicYear> AcademicYears { get; set; }
        public DbSet<ApiPermissionGroup> ApiPermissionGroups { get; set; }
        public DbSet<ApiPermission> ApiPermissions { get; set; }
        public DbSet<ApiRequestHeader> ApiRequestHeaders { get; set; }
        public DbSet<APRequest> APRequests { get; set; }
        public DbSet<AttendanceMarking> AttendanceMarkings { get; set; }
        public DbSet<AttendanceStatu> AttendanceStatus { get; set; }
        public DbSet<AttendanceSubmissionStatu> AttendanceSubmissionStatus { get; set; }
        public DbSet<Block> Blocks { get; set; }
        public DbSet<CommentHeader> CommentHeaders { get; set; }
        public DbSet<Course> Courses { get; set; }
        public DbSet<CourseRequest> CourseRequests { get; set; }
        public DbSet<CourseRequestComment> CourseRequestComments { get; set; }
        public DbSet<Credit> Credits { get; set; }
        public DbSet<Department> Departments { get; set; }
        public DbSet<Dorm> Dorms { get; set; }
        public DbSet<DutyTeam> DutyTeams { get; set; }
        public DbSet<ExternalApi> ExternalApis { get; set; }
        public DbSet<Faculty> Faculties { get; set; }
        public DbSet<Fingerprint> Fingerprints { get; set; }
        public DbSet<GoogleCalendar> GoogleCalendars { get; set; }
        public DbSet<GradeTable> GradeTables { get; set; }
        public DbSet<GradeTableEntry> GradeTableEntries { get; set; }
        public DbSet<LibraryPass> LibraryPasses { get; set; }
        public DbSet<Permission> Permissions { get; set; }
        public DbSet<Preference> Preferences { get; set; }
        public DbSet<RegistrationRequest> RegistrationRequests { get; set; }
        public DbSet<RequestableCourse> RequestableCourses { get; set; }
        public DbSet<SeatingChart> SeatingCharts { get; set; }
        public DbSet<SeatingChartSeat> SeatingChartSeats { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<ServiceAccount> ServiceAccounts { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<StudentCalendarSpecialPermission> StudentCalendarSpecialPermissions { get; set; }
        public DbSet<StudentComment> StudentComments { get; set; }
        public DbSet<StudentSignup> StudentSignups { get; set; }
        public DbSet<Term> Terms { get; set; }
        public DbSet<TimeStampedSignature> TimeStampedSignatures { get; set; }
        public DbSet<Variable> Variables { get; set; }
        public DbSet<WebPage> WebPages { get; set; }
        public DbSet<WebPageTag> WebPageTags { get; set; }
        public DbSet<WednesdaySchedule> WednesdaySchedules { get; set; }
        public DbSet<Weekend> Weekends { get; set; }
        public DbSet<WeekendActivity> WeekendActivities { get; set; }
        public DbSet<WeekendActivityCategory> WeekendActivityCategories { get; set; }
        public DbSet<WeekendDiscipline> WeekendDisciplines { get; set; }
        public DbSet<WeekendDuty> WeekendDuties { get; set; }
    }
}
