//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class WednesdaySchedule
    {
        public int id { get; set; }
        public int TermId { get; set; }
        public System.DateTime Day { get; set; }
        public bool IsABC { get; set; }
    
        public virtual Term Term { get; set; }
    }
}
