//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebhostAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekendDuty
    {
        public WeekendDuty()
        {
            this.Faculties = new HashSet<Faculty>();
        }
    
        public int id { get; set; }
        public int WeekendId { get; set; }
        public string Name { get; set; }
        public System.DateTime DateAndTime { get; set; }
        public int Duration { get; set; }
        public string Description { get; set; }
        public bool IsDeleted { get; set; }
        public string GoogleCalendarEventId { get; set; }
    
        public virtual Weekend Weekend { get; set; }
        public virtual ICollection<Faculty> Faculties { get; set; }
    }
}
